const products={
 boundary:{name:'경계',title:'나를 지키던 이름이\n짐이 되었을 때.',question:'나를 지키던 이름 가운데 이제는 짐이 된 것은 무엇입니까.',image:'scene-descent-v1.jpg',chapter:3,topics:['나를 설명해 온 역할과 이름','보호와 구속을 가르는 경계','다시 받아들일 것과 내려놓을 것']},
 direction:{name:'방향',title:'그리운 곳과\n머물 곳은 다릅니다.',question:'돌아가고 싶은 곳과 지금 머물 수 있는 곳은 어디서 갈라집니까.',image:'scene-return-v1.jpg',chapter:4,topics:['돌아보고 있는 선택의 갈림길','그리움과 필요의 서로 다른 방향','지금의 내가 머물 수 있는 자리']},
 structure:{name:'골조',title:'남은 것은,\n시작할 재료입니다.',question:'남은 것 가운데 내 손으로 다시 다룰 수 있는 것은 무엇입니까.',image:'scene-remains-v1.jpg',chapter:5,topics:['지금 손에 남아 있는 자원','다시 세울 삶의 기준','나의 권한으로 시작하는 작은 재건']}
};
const key='zero-observatory-saved-questions';
let saved=[];try{const value=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(value))saved=[...new Set(value.filter(id=>products[id]))]}catch{}
const dialog=document.querySelector('#product-dialog');let active=null;
function renderSaved(){const list=document.querySelector('#saved-list');list.replaceChildren();if(!saved.length){const p=document.createElement('p');p.className='empty';p.textContent='아직 담아둔 물음이 없습니다.';list.append(p);return}saved.forEach(id=>{const row=document.createElement('div');row.className='saved-row';const open=document.createElement('button');open.textContent=products[id].name+' · '+products[id].title.replace('\n',' ');open.onclick=()=>showProduct(id);const remove=document.createElement('button');remove.textContent='삭제';remove.setAttribute('aria-label',products[id].name+' 물음 삭제');remove.onclick=()=>{saved=saved.filter(item=>item!==id);persist();renderSaved()};row.append(open,remove);list.append(row)})}
function persist(){try{localStorage.setItem(key,JSON.stringify(saved));return true}catch{return false}}
function showProduct(id){if(!products[id])return;active=id;const p=products[id];document.querySelector('#dialog-title').textContent=p.title;document.querySelector('#dialog-category').textContent=p.name+' / DEEP ARCHIVE';document.querySelector('#dialog-question').textContent=p.question;document.querySelector('#dialog-image').src='assets/'+p.image;document.querySelector('#dialog-image').alt=p.name+'의 신화';const topics=document.querySelector('#dialog-topics');topics.replaceChildren(...p.topics.map(text=>{const li=document.createElement('li');li.textContent=text;return li}));document.querySelector('#sample-link').href='result.html#myth-chapter-'+p.chapter;document.querySelector('#save-question').textContent=saved.includes(id)?'담아둔 물음':'이 물음 담아두기';document.querySelector('#save-status').textContent='';dialog.showModal()}
document.querySelectorAll('[data-product]').forEach(button=>button.onclick=()=>showProduct(button.dataset.product));
document.querySelector('.close').onclick=()=>dialog.close();
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close()}});
document.querySelector('#save-question').onclick=()=>{if(!saved.includes(active))saved.push(active);const stored=persist();renderSaved();document.querySelector('#save-question').textContent='담아둔 물음';document.querySelector('#save-status').textContent=stored?'나의 기록에 담았습니다.':'이 브라우저에서는 저장할 수 없어, 현재 화면에서만 유지됩니다.'};
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));document.querySelectorAll('[data-kind]').forEach(card=>card.hidden=button.dataset.filter!=='all'&&card.dataset.kind!==button.dataset.filter)});
renderSaved();const initial=new URLSearchParams(location.search).get('question');if(products[initial])showProduct(initial);
